CREATE TABLE TEST_ADMENU
  (
    id bigint generated BY DEFAULT AS identity (START WITH 1),
    createdBy        VARCHAR(255),
    createdDttm      VARCHAR(14),
    lastModifiedBy   VARCHAR(255),
    lastModifiedDttm VARCHAR(14),
    depth            INTEGER NOT NULL,
    description      VARCHAR(4000),
    displayFlag      BOOLEAN NOT NULL,
    displayOrder     INTEGER NOT NULL,
    menuId           VARCHAR(255),
    menuName         VARCHAR(255),
    targetType       VARCHAR(255),
    url              VARCHAR(255),
    parentAdMenu_id bigint,
    PRIMARY KEY (id)
  ) ;
  
 alter table TEST_ADMENU add constraint FKEF26244F7C0CB3EC foreign key (parentAdMenu_id) references TEST_ADMENU; 