    create table Card (
        id bigint generated by default as identity (start with 1),
        name varchar(255),
        rate integer not null,
        primary key (id)
    )
;

    create table CardPoint (
        id bigint generated by default as identity (start with 1),
        money integer not null,
        point integer not null,
        rate integer not null,
        title varchar(255),
        memberCard_id bigint,
        primary key (id)
    )
;

    create table Member (
        id bigint generated by default as identity (start with 1),
        age integer not null,
        name varchar(255),
        primary key (id)
    )
;

    create table MemberCard (
        id bigint generated by default as identity (start with 1),
        card_id bigint,
        member_id bigint,
        primary key (id)
    )
;

    create table TEST_ADMENU (
        id bigint generated by default as identity (start with 1),
        createdBy varchar(255),
        createdDttm varchar(14),
        lastModifiedBy varchar(255),
        lastModifiedDttm varchar(14),
        depth integer not null,
        description varchar(4000),
        displayFlag boolean not null,
        displayOrder integer not null,
        menuId varchar(255),
        menuName varchar(255),
        targetType varchar(255),
        url varchar(255),
        parentAdMenu_id bigint,
        primary key (id)
    )
;

    alter table CardPoint 
        add constraint FK680174409D5FBB01 
        foreign key (memberCard_id) 
        references MemberCard
;

    alter table MemberCard 
        add constraint FK26D978EAA4CF15F1 
        foreign key (member_id) 
        references Member
;

    alter table MemberCard 
        add constraint FK26D978EA2F649FB 
        foreign key (card_id) 
        references Card
;

    alter table TEST_ADMENU 
        add constraint FKEF26244F7C0CB3EC 
        foreign key (parentAdMenu_id) 
        references TEST_ADMENU
;
